# Generated by Django 5.0.7 on 2024-07-14 13:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leads",
            options={"verbose_name_plural": "Leads"},
        ),
    ]
