# Generated by Django 5.0.7 on 2024-07-17 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0002_alter_leads_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="agent",
            old_name="User",
            new_name="user",
        ),
    ]
